//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wielding_2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main_Tables
    {
        public string Drawing_Number { get; set; }
        public string Line_Number { get; set; }
        public string Line_Class { get; set; }
        public int ID { get; set; }
    }
}
