//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wielding_2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopTest
    {
        public Nullable<double> Item_Number { get; set; }
        public string Weld_Number { get; set; }
        public string Intitial_Production { get; set; }
        public string Drawing_Number { get; set; }
        public string Line_Number { get; set; }
        public string Line_class { get; set; }
        public string Material_Type_Side_A { get; set; }
        public string Material_Type_Side_B { get; set; }
        public string Material_grade_Side_A { get; set; }
        public string Material_grade_Side_B { get; set; }
        public string Pipe_fitting_number_side_A_side_B { get; set; }
        public string Heat_number_side_A_side_B { get; set; }
        public string Spool_No_ { get; set; }
        public string Weld_Type { get; set; }
        public string Thickness__mm_ { get; set; }
        public string Diameter__inch_ { get; set; }
        public string Weld_process { get; set; }
        public Nullable<System.DateTime> Fit_up_date { get; set; }
        public string Fit_up_inspection_QR_number { get; set; }
        public int Id { get; set; }
    }
}
